### PR TITLE
Add colorable-dominant dependency

### LINKED ISSUE #12: Extract get-wcga-colors
I'm loving what this library does. Unfortunately it is very limited to a React stack.

I want to ask If it make senses for you extract the main logic (WCAG Compliant Colors) in a separate module, easy to use indepent of your project stack.

It also can have the flexibility to use a different extractor color than `ColorThief`.

I'm suggesting in build a separate module since [this line](https://github.com/FormidableLabs/react-image-palette/blob/master/src/get-image-palette.js#L153).

An example of using it in inside `react-image-palette`:

```js
const palette = getColorPalette(image, colorThief)

// palette should be something like [ '#3c0c1c', '#fa4c2c', '#4a272d', '#834a3b' ] 
// no matters how you get the colors
const compliantColors = getContrastPalette(palette)

// It returns an array of object like
// [{ color, score, contrast }, { color, score, contrast }, { color, score, contrast }]

/* the rest of your logic for get backgroundColor, color and alternativeColor */
```

What do you think?

### PR DESCRIPTION
**Pull request by Kikobeats**
Hello,

I converted the main logic of this moudle into a separated module called [colorable-dominant](https://github.com/Kikobeats/colorable-dominant) and connect it.

It makes possible use a whatever predominant color extractor and it doesn't break your API.

I hope you like it 😄

Closes #12

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@Kikobeats -- Thanks for the idea, but it does look like you've literally copy-and-pasted this project's source to your new project without attribution:

E.g.:

```js
# react-image-palette
function getMostDominantPrimaryColor(WCAGCompliantColorPairs: ColorPairingMap) {
  var highestDominanceScore = 0;
  var mostDominantColor = "";
  for (var dominantColor in WCAGCompliantColorPairs) {
    var pairs = WCAGCompliantColorPairs[dominantColor];
    var dominance = getPixelDominance(dominantColor);
    var totalPairScore = calculateTotalPairScore(pairs);
    var score = pairs.length ? (pairs.length + totalPairScore) * dominance : 0;
    if (score > highestDominanceScore) {
      highestDominanceScore = score;
      mostDominantColor = dominantColor;
    }
  }
  sortPairsByScore(WCAGCompliantColorPairs[mostDominantColor]);
  return mostDominantColor;
}
```

```js
# colorable-dominant - current master
const getMostDominantPrimaryColor = (colors, WCAGCompliantColorPairs) => {
  var highestDominanceScore = 0
  var mostDominantColor = ''

  for (const dominantColor in WCAGCompliantColorPairs) {
    const pairs = WCAGCompliantColorPairs[dominantColor]
    const dominance = getColorDominance(dominantColor, colors)
    const totalPairScore = calculateTotalPairScore(pairs)
    const score = pairs.length ? (pairs.length + totalPairScore) * dominance : 0
    if (score > highestDominanceScore) {
      highestDominanceScore = score
      mostDominantColor = dominantColor
    }
  }

  WCAGCompliantColorPairs[mostDominantColor] = sortPairsByScore(
    WCAGCompliantColorPairs[mostDominantColor]
  )

  return mostDominantColor
}

# Initial import
const getMostDominantPrimaryColor = (colors, WCAGCompliantColorPairs) => {
  var highestDominanceScore = 0
  var mostDominantColor = ''

  for (const dominantColor in WCAGCompliantColorPairs) {
    const pairs = WCAGCompliantColorPairs[dominantColor]
    const dominance = getColorDominance(dominantColor, colors)
    const totalPairScore = calculateTotalPairScore(pairs)
    const score = pairs.length ? (pairs.length + totalPairScore) * dominance : 0
    if (score > highestDominanceScore) {
      highestDominanceScore = score
      mostDominantColor = dominantColor
    }
  }

  sortPairsByScore(WCAGCompliantColorPairs[mostDominantColor])
  return mostDominantColor
}
```

Although, of course, forks are cool with proper licensing attribute it appears the code is literally copied-and-pasted (with a different code styling applied), without preserving the licensing...

All in all, I think the best bet might be for @aweary to make a new FormidableLabs project with our existing source code with a similar extraction (which I'm sure he'd welcome help on) so that Brandon and Formidable get to continue our own work going forward (and with the right licensing attribution).

**Comment by Kikobeats** [comment]
as I said at first comment:

> I converted the main logic of this module into a separated module called colorable-dominant and connect it.

I'm not understand why are you trying to compare code trying to demostrate something. lol.

Also, I added a copy on readme:

> Similar to react-image-palette but out of the box.

and the license is the same...

**Comment by ryan-roemer** [comment]
Hi @Kikobeats 

## Copyright law

Without being too heavy-handed / "lawyerly", I'm showing that you've literally copy-and-pasted code from `react-image-palette` meaning that you are creating a derivate work under copyright law and subject to the license that we've placed on the code. Not to worry, this isn't too onerous a burden in an OSS project where you've chosen the same license (MIT) as the code you've copied from. The issue is that you've stripped the copyright line in the license: https://github.com/FormidableLabs/react-image-palette/blob/master/LICENSE.txt#L3

```
Copyright (c) 2017 Formidable Labs
```

And replaced it with your own: https://github.com/Kikobeats/colorable-dominant/blob/master/LICENSE#L3

```
Copyright © 2017 Kiko Beats <josefrancisco.verdu@gmail.com> (kikobeats.com)
```

The easiest remedy if you wish to keep your library is just preserve the Formidable ownership as well with something like:

```
Copyright © 2017 Kiko Beats <josefrancisco.verdu@gmail.com> (kikobeats.com)
Copyright © 2017 Formidable Labs
```

## Extractable project

I spoke with @aweary and his plan is to set up lerna for this repo and extract a module along these lines from the existing code and maybe also do some targetted releases for things like `preact`, etc. We'd love for your help if something fits a need / interest!

**Comment by Kikobeats** [comment]
@ryan-roemer this is totally different than you said as first comment.

I don't remove the original license; simply I auto-generate the scaffold based on my github credentials, so the copy was not correct.

I updated the authorship: https://github.com/Kikobeats/colorable-dominant/commit/4a273fa3e10a5598c5432b5e85eb7df49776c8cf 👍

**Comment by ryan-roemer** [comment]
@Kikobeats -- thanks for updating the authorship!

I'll let @aweary take it from here as to technical direction (take this as a dep vs. doing lerna and multi-modules for various purposes (this type of extractor included) within this project) and hopefully we end up with something that works with everyone's needs!

**Comment by aweary** [comment]
I'm going to close this in favor of https://github.com/FormidableLabs/react-image-palette/pull/14, which implements the `image-palette-core` package (`image-palette` was taken 😭 ).

**Comment by Kikobeats** [comment]
why is better?

**Comment by ryan-roemer** [comment]
The monorepo allows us to:

1. Keep all the code lock step without requiring a dep on a not-in-our-org repo project.
2. Add additional packages (like for vue, etc.) easily

Also, since the original image-palette code that has been extracted to a separate package was all Brandon's work to begin with, makes sense to keep it here :)

Hopefully the separate package in #14 solves your needs -- feel free to open any issues or changes to that package if you see a need!

**Comment by Kikobeats** [comment]
not the monorepo, I mean, the code.

The idea is my implementation is be independiente of `color-thief`.

The `image-palette-core` package is basically moving a dependency and copy/paste code in a separate package, so I don't see benefits there. 

Meanwhile I isolated the core concept in a package; not depencies, just API compromise.

**Comment by ryan-roemer** [comment]
I'm guessing @aweary would be open to a PR that made `image-palette-core` (and transitively the other packages) accept something pluggable in place of `color-thief` if desired.

**Comment by aweary** [comment]
@ryan-roemer is correct, I definitely want to make `image-palette-core` more flexible and I will totally consider adopting the changes you made in `colorable-dominant` after #14 is merged.

**Pull request closed without merging**
